## Pertemuan 7 / Pengenalan Tensorflow

In [44]:
import tensorflow as tf
import numpy as np

In [8]:
tf.constant([1, 2, 3, 4], shape=[2, 2], dtype=tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [10]:
tf.zeros(shape=[8, 3], dtype=tf.int64)

<tf.Tensor: shape=(8, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)>

In [12]:
fill_d = tf.fill([4,4], 9)

fill_d.numpy()

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [16]:
tf.random.normal([4, 4], mean=0, stddev=1, seed=1).numpy()

array([[ 1.0080464 , -1.3288287 , -0.6130567 , -1.9524803 ],
       [ 0.5884956 ,  0.7566981 ,  0.19659884,  0.15151589],
       [ 0.10186929,  0.38480574,  1.7378565 ,  1.6991341 ],
       [ 1.0799859 ,  0.6563117 , -0.53183275,  2.0500531 ]],
      dtype=float32)

In [22]:
list = [[1,2],[3,4]]

tf.convert_to_tensor(list, dtype=tf.int64).numpy()

array([[1, 2],
       [3, 4]], dtype=int64)

In [37]:
var_1 = tf.Variable(tf.zeros([2,3]))

In [38]:
var_1.read_value()

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [39]:
var_value_1 = [[1,2,3],[4,5,6]]
var_1.assign(var_value_1)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [40]:
var_1.read_value()

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Slicing dan indexing

In [88]:
var_random = tf.random.normal([16,16,32,64])
var_random

<tf.Tensor: shape=(16, 16, 32, 64), dtype=float32, numpy=
array([[[[-3.99693437e-02,  1.48018956e-01, -6.01273477e-01, ...,
           5.55718690e-02,  3.26375753e-01, -1.42455900e+00],
         [-1.05542326e+00,  1.25430179e+00,  8.88521791e-01, ...,
          -7.84997284e-01,  2.26182535e-01,  7.40584582e-02],
         [-1.02088690e+00, -5.97112060e-01,  6.82103693e-01, ...,
           4.00183827e-01,  1.31671810e+00,  8.21477175e-01],
         ...,
         [-1.65631139e+00,  1.82917345e+00, -1.66836143e-01, ...,
           2.01006866e+00,  1.50911912e-01, -1.64819968e+00],
         [-1.96615204e-01, -8.90705884e-01,  3.74448687e-01, ...,
           6.88480794e-01,  1.50994766e+00, -1.69844413e+00],
         [ 6.96820378e-01, -3.92499536e-01, -1.59049070e+00, ...,
          -1.63097632e+00, -1.48289609e+00,  3.18090528e-01]],

        [[-5.65815389e-01, -1.85379136e+00, -5.54087460e-01, ...,
          -1.23854005e+00, -1.08569145e+00,  1.22269237e+00],
         [ 9.06110823e-01,  4.

In [50]:
var_random[2:3]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.7210636 ,  1.7979423 ,  1.1056465 , -0.22183427]],
      dtype=float32)>

In [56]:
var_random[1][2][1]

-0.9100029

In [89]:
tf.gather(var_random, axis=0, indices=[0,2,1,1])

<tf.Tensor: shape=(4, 16, 32, 64), dtype=float32, numpy=
array([[[[-3.99693437e-02,  1.48018956e-01, -6.01273477e-01, ...,
           5.55718690e-02,  3.26375753e-01, -1.42455900e+00],
         [-1.05542326e+00,  1.25430179e+00,  8.88521791e-01, ...,
          -7.84997284e-01,  2.26182535e-01,  7.40584582e-02],
         [-1.02088690e+00, -5.97112060e-01,  6.82103693e-01, ...,
           4.00183827e-01,  1.31671810e+00,  8.21477175e-01],
         ...,
         [-1.65631139e+00,  1.82917345e+00, -1.66836143e-01, ...,
           2.01006866e+00,  1.50911912e-01, -1.64819968e+00],
         [-1.96615204e-01, -8.90705884e-01,  3.74448687e-01, ...,
           6.88480794e-01,  1.50994766e+00, -1.69844413e+00],
         [ 6.96820378e-01, -3.92499536e-01, -1.59049070e+00, ...,
          -1.63097632e+00, -1.48289609e+00,  3.18090528e-01]],

        [[-5.65815389e-01, -1.85379136e+00, -5.54087460e-01, ...,
          -1.23854005e+00, -1.08569145e+00,  1.22269237e+00],
         [ 9.06110823e-01,  4.3

In [90]:
tf.gather_nd(var_random, indices= [[1,1],[2,2]])

<tf.Tensor: shape=(2, 32, 64), dtype=float32, numpy=
array([[[ 0.07818916,  0.10579839, -0.75112456, ..., -1.0493832 ,
          0.04572106,  0.6205031 ],
        [-0.518469  , -0.32802436,  0.0654102 , ..., -1.1538241 ,
         -0.745535  , -2.042611  ],
        [-1.2863183 ,  0.70980674, -0.7461774 , ..., -0.5544682 ,
         -0.5285256 , -0.3940508 ],
        ...,
        [ 0.01670142,  0.2379214 , -0.38585284, ...,  0.09262706,
         -1.3031894 , -0.9660891 ],
        [ 0.29646507,  0.75466233,  0.57833445, ..., -0.00924754,
          0.75631243, -0.03298602],
        [-0.5639597 , -0.94031566,  0.49096447, ..., -1.1655148 ,
          1.790134  , -2.1130476 ]],

       [[ 1.2999951 , -0.11348221,  0.6659176 , ...,  0.8323639 ,
          0.18318419,  0.5591216 ],
        [ 0.33641538,  0.97841865, -0.5221013 , ..., -0.45784226,
         -1.6918062 , -0.3522573 ],
        [ 0.24039954,  0.21998443, -0.53995234, ...,  0.50618476,
         -0.6635942 , -0.30806592],
        ...,
 

In [91]:
var_random.get_shape()

TensorShape([16, 16, 32, 64])

In [92]:
tf.reshape(var_random, (64, 16, 32, 16)) # harus sama jumlah isinya dengan cara dikali = dengan shape awal

<tf.Tensor: shape=(64, 16, 32, 16), dtype=float32, numpy=
array([[[[-3.99693437e-02,  1.48018956e-01, -6.01273477e-01, ...,
          -1.81810096e-01, -7.04095662e-01,  6.04341030e-01],
         [-1.11998367e+00, -7.97151685e-01, -1.23063564e+00, ...,
           5.93857408e-01,  2.50897080e-01,  3.40039968e-01],
         [-2.81184852e-01, -2.93372095e-01, -1.89014181e-01, ...,
          -1.01937199e+00, -5.49336374e-01, -8.16004813e-01],
         ...,
         [-5.12777984e-01, -7.56301343e-01, -1.07129228e+00, ...,
          -2.25073293e-01, -4.66341138e-01,  8.41680646e-01],
         [ 1.46960187e+00,  3.84211570e-01,  1.35836554e+00, ...,
           1.53087258e+00, -6.34488761e-01,  2.14555454e+00],
         [-2.83111602e-01, -6.46690786e-01, -1.53095984e+00, ...,
           1.94510773e-01, -5.69154084e-01, -4.28801961e-02]],

        [[-1.47083855e+00, -5.65218210e-01,  1.12347627e+00, ...,
          -1.56430197e+00,  2.87678450e-01,  5.40252805e-01],
         [ 2.10405421e+00,  2.

In [93]:
print(var_random.shape)
var_random1 = tf.reshape(var_random, (64,16,32,16))
print(var_random1.shape)

(16, 16, 32, 64)
(64, 16, 32, 16)


### Expand Dimension

In [94]:
print(var_random.shape)
var_random1 = tf.expand_dims(var_random, axis=1)
print(var_random1.shape)

(16, 16, 32, 64)
(16, 1, 16, 32, 64)


### Squeezeing

In [96]:
print(var_random1.shape)
var_random1 = tf.squeeze(var_random1, axis=3)
print(var_random1.shape)

(16, 1, 16, 32, 64)


InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[3], expected a dimension of 1, got 32 [Op:Squeeze]

### Operator Aritmatika

In [97]:
a = tf.constant([[2,3], [4,5]])
b = tf.constant([[9,8], [6,7]])

In [98]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 11],
       [10, 12]])>

In [99]:
tf.subtract(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-7, -5],
       [-2, -2]])>

In [100]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 24],
       [24, 35]])>

In [101]:
tf.divide(a,b)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.22222222, 0.375     ],
       [0.66666667, 0.71428571]])>

In [102]:
tf.math.log(a,b)

TypeError: Cannot convert ' name: ' to EagerTensor of dtype int32

In [103]:
tf.pow(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  512,  6561],
       [ 4096, 78125]])>

In [104]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 37],
       [66, 67]])>

In [119]:
sample = tf.constant([[1,1,3], [4,4,6], [7,9,9]])

In [120]:
sample.numpy()

array([[1, 1, 3],
       [4, 4, 6],
       [7, 9, 9]])

In [121]:
tf.argmax(sample, axis=0).numpy()

array([2, 2, 2], dtype=int64)

In [122]:
tf.argmax(sample, axis=1).numpy()

array([2, 2, 1], dtype=int64)

In [ ]:
tf.concat([tesor1, tensor2], axis=0)

### Eager Execution Tensorflow

In [123]:
tf.__version__

'2.10.0'